## Créer un array NumPy

In [12]:
import numpy as np

revenus = [1800, 1500, 2200, 3000, 2172]

revenu_array = np.array(revenus)

revenu_array

array([1800, 1500, 2200, 3000, 2172])

## Quelques fonctions de base

### Array avec les zeros

In [6]:
array_zero = np.zeros([5,2])
print(array_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Array des uns

In [7]:
array_un = np.ones([3,4])
array_un

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Array avec une sequence lineaire : arange

In [10]:
array_lineare = np.arange(1,15,2)
array_lineare

array([ 1,  3,  5,  7,  9, 11, 13])

### Array de n valeurs espacées : linspace

In [11]:
array_espace = np.linspace(1,15, 100)
array_espace

array([ 1.        ,  1.14141414,  1.28282828,  1.42424242,  1.56565657,
        1.70707071,  1.84848485,  1.98989899,  2.13131313,  2.27272727,
        2.41414141,  2.55555556,  2.6969697 ,  2.83838384,  2.97979798,
        3.12121212,  3.26262626,  3.4040404 ,  3.54545455,  3.68686869,
        3.82828283,  3.96969697,  4.11111111,  4.25252525,  4.39393939,
        4.53535354,  4.67676768,  4.81818182,  4.95959596,  5.1010101 ,
        5.24242424,  5.38383838,  5.52525253,  5.66666667,  5.80808081,
        5.94949495,  6.09090909,  6.23232323,  6.37373737,  6.51515152,
        6.65656566,  6.7979798 ,  6.93939394,  7.08080808,  7.22222222,
        7.36363636,  7.50505051,  7.64646465,  7.78787879,  7.92929293,
        8.07070707,  8.21212121,  8.35353535,  8.49494949,  8.63636364,
        8.77777778,  8.91919192,  9.06060606,  9.2020202 ,  9.34343434,
        9.48484848,  9.62626263,  9.76767677,  9.90909091, 10.05050505,
       10.19191919, 10.33333333, 10.47474747, 10.61616162, 10.75

### Accéder au type d'élément d'un array : dtype

In [13]:
revenu_array.dtype

dtype('int32')

### Selectionner les éléments d'un array 

#### Selectionner un seul élément

In [15]:
print(revenu_array[2])
revenu_array[-1]

2200


2172

#### Selectionner un ensemble d'éléments

In [16]:
print(revenu_array[1:3])

[1500 2200]


#### Sélectionner plusieurs éléments sur condition

In [17]:
print(revenu_array[revenu_array>2000])

[2200 3000 2172]


In [19]:
revenu_array > 2000

array([False, False,  True,  True,  True])

### Autres méthodes NumPy

#### Dimension d'un array : shape

In [20]:
revenu_array.shape

(5,)

#### Moyenne d'un array : mean()

In [21]:
revenu_array.mean()

2134.4

#### Maximum ou minimum d'un array : max() ou min()

In [22]:
print(revenu_array.max())
print(revenu_array.min())

3000
1500


#### Indice du Max ou du Min : argmax() ou argmin()

In [23]:
print(revenu_array.argmax())
print(revenu_array.argmin())

3
1
